services:
  backend:
    build:
      context: ./backend
    container_name: tripsathi-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"

  admin:
    build:
      context: ./Admin
    container_name: tripsathi-admin
    restart: unless-stopped
    env_file:
      - ./Admin/.env
    ports:
      - "3000:3000"